export const dataTextUk = {
    lang:"uk",
    text_premiere:"Прем'єра",
    home_btn:' Повернутися',
    schedule:{
        title:'Розклад',
        time_text:' Час ',
        price_text:' Ціна ',
        date_text:'Дата : ',
        row_text:' Ряд: ',
        place_text:' Місце: ',
    },
    movies_section:{
        title:'Фільми.',
        error_text:'Фільм не знайдено.',
        error_text1:'Натисніть значок, щоб переглянути всі.',
        prev_btn:'Попередня',
        next_btn:'Наступна',
        page:'Сторінка ',
        home_btn:'На головну',
    },
    stars_section:{
        title:'Популярні актори',
        details_title:'Фільми за участю цього актора.'
    },
    details_section:{
        genres_title:'Жанри :',
        trailer_btn:'Переглянути трейлер',
        schedule_title:'Розклад сеансів та вартість квитків.',
        choose_btn:'Обрати місце',
        info_title:'Опис',
        companies_title:'Виробництво :',
    },
    tiket_page:{
        story_title:'Історія бронювання',
        ticket_title:'Мої квитки:',
        hall_title:'Оберіть місце',
        occup_seat:'Зайняте місце',
        free_space:'Вільне місце',
        select_space:'Обране місце',
        form_title:'Ваші квитки:',
        total_price: 'Загальна сума: ',
        reser_seats_btn:'Резерв місць',
        set_date:'Дата сеансу: ',
        set_time:'Час сеансу: ',
        modal_title:'Приємного перегляду!',
    },
    contacts:{
        title:'Контакти розробника:',
        btn_text:'Ще контакти ...',
    },
    footer_date:'10 Вересеня 2023р.',
}